### ISSUE TITLE
Reporting status mockups

### ISSUE THREAD

**Issue by angela-smithers** [GSA/sdg-indicators#445]
![graphic-layout](https://cloud.githubusercontent.com/assets/16124816/22217607/a932a57a-e171-11e6-9fea-e4f10da169fe.png)
![graphic-layout-notation](https://cloud.githubusercontent.com/assets/16124816/22217615/aec02328-e171-11e6-98ee-d9097ce991f7.png)

**Comment by philipashlock** [comment]
From @angela-smithers on #452

Indicators 1 and 2 show the same layout idea.
Indicator 3 shows another idea; much smaller, harder to read.

![graphic-layout-5](https://cloud.githubusercontent.com/assets/16124816/22345156/f785a102-e3cc-11e6-90a7-db634201c585.png)
![graphic-layout-6](https://cloud.githubusercontent.com/assets/16124816/22345168/06857092-e3cd-11e6-8894-bd8cb84a7147.png)

**Comment by philipashlock** [comment]
Original prototype can be seen at http://jjediny.github.io/jkan/dashboard/

**Comment by JenPark9** [comment]
https://cloud.githubusercontent.com/assets/16124816/22345156/f785a102-e3cc-11e6-90a7-db634201c585.png

**Comment by shaneporter** [comment]
hi @JenPark9 - here's the screenshot of a dashboard prototype I received from you, updating github:

![image](https://cloud.githubusercontent.com/assets/2493614/22515635/0b2f2dae-e89b-11e6-9e44-7998bf027e67.png)

**Comment by JenPark9** [comment]
Thank you, Shane! (How did you do that?)

**Comment by shaneporter** [comment]
1. Took a screenshot of the PowerPoint.
2. Opened in Photoshop, cropped the image.
3. Copied the image (CTRL + C)
4. With focus on the comment, pasted it in, using CTRL + V.

I'm probably being unnecessarily complete here - the most important steps are 3 and 4.

You should see immediate visual feedback after 4, that something is happening.

**Comment by JenPark9** [comment]
☺ I guess something is “happening.”
I am going to post a few more links from NGOs that are looking to provide platforms for the SDGs. We could chat about them during our next call if there is interest.
Thank you!

**Comment by angela-smithers** [comment]
![graphic-layout-v3](https://cloud.githubusercontent.com/assets/16124816/22746978/ad39f68a-edf3-11e6-81f4-07c2a63e071b.jpg)
![graphic-layout-v3-with-notes](https://cloud.githubusercontent.com/assets/16124816/22746981/af6687ca-edf3-11e6-8bb7-7268467cbab8.jpg)

**Comment by angela-smithers** [comment]
![graphic layout v3-03](https://cloud.githubusercontent.com/assets/16124816/22829724/f7bb4856-ef71-11e6-9cc1-4fe2623788fb.jpg)
![graphic layout v3-04](https://cloud.githubusercontent.com/assets/16124816/22829725/f9d74bbc-ef71-11e6-84e7-8e80a58b8ff8.jpg)

outlines are added; the red hex color is #ff0000 or whatever is compliant; the red of the 'Goal' icon remains unchanged due to proprietary matters.

**Comment by angela-smithers** [comment]
![grayscale-layout-v3](https://cloud.githubusercontent.com/assets/16124816/22831168/548d0a9c-ef77-11e6-9f83-1e56ad308e37.jpg)

This is a version using grayscale. The progression is similar to what you would see on active.com when registering for RunDisney

**Comment by JenPark9** [comment]
Angela,
Thank you for this. I am thinking that the Reporting Status by Goal page would be under the Reporting Status tab, and would not need the list on the left. Then, for each reporting status by goal, we would want the thermometer approach, not the single button approach.

So, it would be 
Reporting Status by Goal
Goal 1 ICON Poverty
End poverty in all its forms everywhere
[xxxxx--000]
Where 
x=green/reported
--=yellow/producing statistics
000=red/exploring data sources
and the amount of each color in the thermometer would be driven by the percentage of that goal's indicators by status.
So, if Goal 1 had 10 indicators, then xxxx=5 of 10 or 50% green reported
--=2 of 10 or 20% yellow/producing statistics
000=3 or 10 or 30% red/exploring data sources
And this would be repeated for each goal.

The Reporting Status by Indicator might appear by clicking the icon under the Reporting Status by Goal page, and/or replace the current list of indicators under the Statistics tab.

**Comment by rtwell** [comment]
for these status markers: 
![image](https://cloud.githubusercontent.com/assets/12564977/22981473/1c8d7f48-f362-11e6-9e5a-d2e2ffd446ff.png)
I think these run the risk of looking like switches, rather than indicators or status bars. I wonder if we could use a single status mark per indicator? While this example is not accessible, it demonstrates what I mean:
![image](https://cloud.githubusercontent.com/assets/12564977/22982058/903e7194-f363-11e6-80e8-7bd6c363605d.png)
To be accessible, the far right column would need a letter or an icon per status for folks with visual impairments. 
Does this make sense?

**Comment by JenPark9** [comment]
Thanks, Ryan. We have moved on from those icons for the same reasons you’ve mentioned. I think Angela has the latest. Stay tuned!

**Comment by shaneporter** [comment]
hi @rtwell, I'm Shane, and I'm working on the UK SDGs website.

The single status mark per indicator is a good way to go; perhaps it could be bigger, with text inside it. In addition, a specific shape be used to visually distinguish them.

**Comment by JenPark9** [comment]
A few other thoughts
So, the indicator status is an ordered categorical variable. So, we need discrete icons displaying "progress" without implying how much progress.

What if we used the moon style used by consumer reports? A full moon = not started, half moon=in process, new moon (black)=done.
🌕🌓🌑
Or, we could do a task list: box= to do, swirl=work underway, check=done.
◻🌀 ✅
Or, an evocative icon: magnifying glass=we are looking for data, clock=working on production, graph=statistics reported.
🔍🕙📊

**Comment by ChristalynSM** [comment]
I like the evocative icon idea, but I wonder if it will require a little more effort from users to decode what we mean compared to the moon style, which only requires a glance to realize it's communicating progress status.  

Like the moon idea, we could consider using a speedometer image.  The arrow pointing at the 0, 50, and 100 positions respectively.  This could also incorporate color, starting with red on the left side of the speedometer and transitioning to green on the right side.  Something sort of like this: 

![image](https://cloud.githubusercontent.com/assets/21144812/23027805/7cfae506-f433-11e6-83fa-6c3fba7c6d26.png)

**Comment by JenPark9** [comment]
This is good with its simplicity, but the outcomes being measured are not continuous and the dial could suggest otherwise.  (The reporting status for an indicator could not be 33% complete, for example.)

Sent from my iPhone

On Feb 16, 2017, at 10:35 AM, Christalyn Steers McCrum <notifications@github.com<mailto:notifications@github.com>> wrote:


I like the evocative icon idea, but I wonder if it will require a little more effort from users to decode what we mean compared to the moon style, which only requires a glance to realize it's communicating progress status.

Like the moon idea, we could consider using a speedometer image. The arrow pointing at the 0, 50, and 100 positions respectively. This could also incorporate color, starting with red on the left side of the speedometer and transitioning to green on the right side. Something sort of like this:

[image]<https://cloud.githubusercontent.com/assets/21144812/23027805/7cfae506-f433-11e6-83fa-6c3fba7c6d26.png>

-

**Comment by angela-smithers** [comment]
Using the Font Awesome icons, here are some quick layouts/views for the latest suggestions:
![graphic-layout-v4-2](https://cloud.githubusercontent.com/assets/16124816/23071297/d3573da0-f4fb-11e6-91c9-0494b5c2cc53.jpg)
This would be fa-circle-o [&#xf10c;], fa-adjust [&#xf042;], fa-circle [&#xf111;]

**Comment by angela-smithers** [comment]
![graphic-layout-v4-3](https://cloud.githubusercontent.com/assets/16124816/23071549/ba049d56-f4fc-11e6-90c9-c855de5ff212.jpg)
This would be fa-search [&#xf002;], fa-clock-o [&#xf0017;], fa-bar-chart [&#xf080;]

**Comment by angela-smithers** [comment]
Working on one more ...

**Comment by angela-smithers** [comment]
For more icons, here is a link to the Font Awesome cheat sheet : http://fontawesome.io/cheatsheet/

**Comment by angela-smithers** [comment]
![graphic-layout-v5](https://cloud.githubusercontent.com/assets/16124816/23365644/c8228948-fcd1-11e6-8ced-f9bb9a0c2040.jpg)

This is a version combining the stop light idea with the symbol idea.  Hopefully, it is a great marriage.
Please reply with comments and/or questions

**Comment by JenPark9** [comment]
Angela,
Looking good!
A. Can we reduce the size of the traffic lights to maybe 2/3 of the current size? 
B. Can we invert the color of the circle and the interior symbol? So, the checkmark is green against a white background, for example? This may reduce any confusion between the goal icon color and the traffic light.
C. Can we remove the < in the thermometer and change the percentages shown to sum to 100%? This will help us keep things straight conceptually.
D. Can we move the key to appear flush right with the goal title (in this case, flush right with End poverty in all its forms everywhere)?

**Comment by angela-smithers** [comment]
![layout-v6](https://cloud.githubusercontent.com/assets/16124816/23519501/1cef79f2-ff45-11e6-852e-03b9e9d54fa6.jpg)

**Comment by angela-smithers** [comment]
![icons-march2017-10](https://cloud.githubusercontent.com/assets/16124816/23553851/8bffa550-fff0-11e6-8904-8c3a233c4a3a.png)
![icons-march2017-08](https://cloud.githubusercontent.com/assets/16124816/23553852/8bffc008-fff0-11e6-9ba9-d71d7fc32a8c.png)
![icons-march2017-09](https://cloud.githubusercontent.com/assets/16124816/23553853/8c038e36-fff0-11e6-8737-019faee59599.png)

**Comment by angela-smithers** [comment]
![layout-v7](https://cloud.githubusercontent.com/assets/16124816/23561371/f53a2bce-000b-11e7-80af-df8adbde5e07.jpg)

**Comment by angela-smithers** [comment]
An Accessibility compliant red :: #FF0000 works.

**Comment by angela-smithers** [comment]
![icons-13march2017](https://cloud.githubusercontent.com/assets/16124816/23864759/e00942b8-07e9-11e7-9e88-c787554efe58.png)
Note: (#1a1a1a + #4aa564),
(#1a1a1a + #ff0000)
(#1a1a1a + #f9c642)

**Comment by AnnCorp** [comment]
Hello All
I recently shared with some UK SDGs colleagues the mockup versions I received from @JenPark9  last week. I hope the following feedback is helpful and please do let us know if you have any comments on any of this:

1. Re having the one word goal description eg 'water' and the full goal description - do we need both? Instead of the one word should we use the headings used in the global goals icons instead eg 'clean water and sanitation', especially where a word like 'water' appears in multiple goal descriptions. If we use the global goals description, do we need the full description too?

2. It could be helpful to have more clarity on the numbers of indicators represented by the coloured blocks and maybe have the total number of indicators more closely aligned to the progress coloured bars. Having percentages makes for easier comparison but given the different numbers of indicators, could get the same size block of green, for example, representing different numbers of indicators?

We may also have some further comments next week from Niren Basu, our usability testing lead in the ONS Data Science campus. I hope this would fit with your timings.
If you would find it helpful for us to test any future interactive versions, we would be more than happy to do so.

**Comment by JenPark9** [comment]
Ann,
Thank you so much. This is very good feedback. I am flagging another issue item that displays our most recent thinking on the data dashboard, but does not yet address your very good input. See https://github.com/GSA/sdg-indicators/issues/468.

**Comment by angela-smithers** [comment]
I moved the "Goal Status" images to a separate issue #468 to avoid confusion.  This is the editted version based on comments placed in that Issue #468 
![layout-v9](https://cloud.githubusercontent.com/assets/16124816/24303100/24037502-108b-11e7-8681-4279171d5031.jpg)
