### ISSUE TITLE
Add UNSD global metadata link to indicator metadata page 

### ISSUE THREAD

**Issue by JenPark9** [GSA/sdg-indicators#584]
Remove the current row tab "Method of computation for global SDG indicator."

Add standard across all indicators: UNSD methodology for global SDG indicator, see https://unstats.un.org/sdgs/metadata/files/.

**Comment by philipashlock** [comment]
Rather than add a generic link, this update (98abe615b81df901053f0cf8b75cd64b03cd17dd) provides links to the metadata files for each indicator just like on https://unstats.un.org/sdgs/metadata/ but it does so with blue buttons above the table. Let me know if you'd rather have the links display in some other way.

**Comment by JenPark9** [comment]
I think this is awesome. For the standard language above the global metadata table, let's spell out UNSC to United Nations Statistical Commission. (Sometimes folks think UNSC is the security council, and I am trying to be sensitive to that!) :)

**Comment by JenPark9** [comment]
Also, since as you point out not all global metadata are yet developed, let's update the standard text in this same space to "Complete global metadata documentation on all indicators in Goal 1, unless otherwise noted, is provided by the UN Statistics Division." 
Since Kali is busy w data providers at the moment, maybe Angela can update the master indicator sheet to denote where metadata are not yet available (all tier 3, plus a few tier 1 and 2 where the custodian agency has not yet provided it). Maybe she can suggest what the message should say in those cases?

**Comment by philipashlock** [comment]
I've made this change (with commit 006a800aa341f5e34039253360ee7c2313b37cf1) but when we're satisfied with the text change, we'll need to remember to update the Spanish translation. 

@JenPark9 I'm not sure it makes sense to say "unless otherwise noted" because right now we link to the metadata documentation from the UN for each of the 17 goals. Are there any exceptions? 

Note that we're linking to two different types of metadata documentation from the UN at the top of that metadata tab, one is the documentation for the goal (linked in the text) and the other is documentation for the indicator (linked with the blue buttons). 

@angela-smithers Let me know if you'd like to start updating the [master indicator sheet](https://github.com/GSA/sdg-indicators/blob/gh-pages/data/sdg_indicator_metadata.csv) with details to denote which indicators have these UN links available, I'll want to coordinate with you on the best way to do that beforehand

**Comment by JenPark9** [comment]
Roger that about the Spanish translation. (Angela, could you ask Larry or Francisco?). Re the "unless otherwise noted," we do not have global metadata for each of the indicators yet, and we want to somehow say that the global metadata is not yet available for those indicators (so we do not show an error page.) The text reads (note, I think global should also be in blue font) "global metadata documentation on all indicators in Goal 1, unless otherwise noted, is provided by the UN Statistics Division."  Am I misunderstanding?

**Comment by JenPark9** [comment]
@angela-Smithers, I think you can start w adding the flags for missing global metadata in the master indicator sheet. Thanks!
