### ISSUE TITLE
Data for 7.2.1 not plotted on graph

### ISSUE THREAD

**Issue by philipashlock** [GSA/sdg-indicators#586]
The graph for [7.2.1](https://gsa.github.io/sdg-indicators/7-2-1/) is a flatline on the X axis - no values are being graphed. 

![screen shot 2017-09-15 at 5 12 03 pm](https://user-images.githubusercontent.com/183402/30503731-56334a7e-9a39-11e7-8f1c-6990c5d75837.png)

**Comment by philipashlock** [comment]
@Kali2017SDG The data tables cannot contain symbols like the percent sign (%) so the fix for this is to update the data table with only raw numerical values. Let me know if you'd like me to update the data or have someone else make the correction.

**Comment by JenPark9** [comment]
Phil, can you do? I would but my computer is mort.

Sent from my iPhone

On Sep 15, 2017, at 5:14 PM, Philip Ashlock <notifications@github.com<mailto:notifications@github.com>> wrote:


@Kali2017SDG<>https://github.com/kali2017sdg<> The data tables cannot contain symbols like the percent sign (%) so the fix for this is to update the data table with only raw numerical values. Let me know if you'd like me to update the data or have someone else make the correction.

-

**Comment by Kali2017SDG** [comment]
Please fix data from last year - so when she submits for this year, she'll know to conform to that format. Thanks Philip!

Sent from my iPhone

On Sep 15, 2017, at 5:14 PM, Philip Ashlock <notifications@github.com<mailto:notifications@github.com>> wrote:


@Kali2017SDG<>https://github.com/kali2017sdg<> The data tables cannot contain symbols like the percent sign (%) so the fix for this is to update the data table with only raw numerical values. Let me know if you'd like me to update the data or have someone else make the correction.

-

**Comment by philipashlock** [comment]
Fixed with commit 8c28d5979a739811ed26b5d1c2ad05495053f74a
