### ISSUE TITLE
Error in graph for 17.4.1 (postive and negative values)

### ISSUE THREAD

**Issue by JenPark9** [GSA/sdg-indicators#723]
Please provide the code for the solution so that we can make these changes going forward. Thank you!

**Comment by Kali2017SDG** [comment]
More importantly, I noticed he also changed the data series for the indicator-- completely.  From "US Gross output of Federal Reserve banks, credit intermediation, and related activities as a percentage of exports (goods and services) " to "Net U.S. acquisition of debt securities (outflow) as a percentage of exports (goods and services)  " .... =>may need to put some sort of edit check to flag this type of radical changes going forward (though not sure what at the moment)?

**Comment by philipashlock** [comment]
This was fixed with 3d59c53aeee49a30860ed59c9e6e33532c935bc1

The variable name (column heading) was changed in the CSV file, but the corresponding field in the metadata to flag which variable to graph had not been updated. 

The explanation of the flag in the metadata for displaying negative values is [here](https://github.com/GSA/sdg-indicators/issues/585#issuecomment-329919013), but this should be a short term fix, so I don't know how much we should document. Instead, we can update the code to look for negative values to automatically configure the graph rather than manually set it in the metadata like we're currently doing.
